"""Build one scenario store per Comoros municipality (adm3), three islands.

Inputs
  blob + index   the 600 maximum depth rasters of the three island models,
                 quantized to centimetres on the device and deflated
  com_admin3     the municipality boundaries (55 units, EPSG 4326)
  magnitudes     per municipality RainyDay storm totals, area weighted

Outputs, per municipality
  fim_store/Comoros/fim_store_<PCODE>_<Slug>_v1.zarr(.zip)
  fim_config/Comoros_<Slug>.yaml
  fim_config/aoc/Comoros_<PCODE>_<Slug>_aoc.geojson
plus manifest_Comoros.csv and magnitudes_Comoros_per_unit.json
"""
# NOTE ON PATHS: the constants below are the paths of the machine this was
# built on (the delivered Comoros rasters, the com_admin3 shapefile and the
# magnitude table). Point them at your own copies before rerunning. Needs
# numpy, rasterio, geopandas and zarr.
import csv
import json
import os
import re
import shutil
import sys
import unicodedata
import zipfile
import zlib

import numpy as np
import rasterio
from rasterio.windows import Window
import geopandas as gpd
import zarr

BLOB_DIR = "/mnt/user-data/uploads/FIM_version/Data/_comoros_build/blobs"
INDEX = "/mnt/user-data/uploads/FIM_version/Data/_comoros_build/index_final.json"
REF = "/mnt/user-data/uploads/FIM_version/Data/Comoros/_ref"
SHP = "/mnt/user-data/uploads/FIM_version/Data/Comoros/com_admin_boundaries.shp/com_admin3.shp"
MAGS = "/home/claude/com/magnitudes_Comoros_from_rain.json"
OUT = "/home/claude/com/out"
BUF = 10
EXTENT_M = 0.05
ISLAND_OF = {"KM2": "grande", "KM1": "anjouan", "KM3": "moheli"}
BOX_OF = {"grande": "Comoros_NE_No1", "anjouan": "Comoros_SE_No3", "moheli": "Comoros_SW_No2"}


def slug(name):
    s = unicodedata.normalize("NFKD", str(name)).encode("ascii", "ignore").decode()
    return "".join(p.capitalize() for p in re.split(r"[^A-Za-z0-9]+", s) if p)


def create(group, name, shape, dtype, chunks):
    try:
        return group.create_array(name, shape=shape, dtype=dtype, chunks=chunks)
    except (AttributeError, TypeError):
        return group.create_dataset(name, shape=shape, dtype=dtype, chunks=chunks)


def load_island_stack(island, index):
    """(200, H, W) uint16 centimetres, ordered sample_0001..sample_0200."""
    ent = sorted((e for e in index if e["island"] == island), key=lambda e: e["sample"])
    H, W = ent[0]["H"], ent[0]["W"]
    stack = np.empty((len(ent), H, W), dtype="uint16")
    ids = []
    for k, e in enumerate(ent):
        with open(os.path.join(BLOB_DIR, e["blob"]), "rb") as f:
            f.seek(e["start"])
            raw = zlib.decompress(f.read(e["csize"]))
        stack[k] = np.frombuffer(raw, dtype="<u2").reshape(H, W)
        ids.append(e["sample"])
    return ids, stack


def zip_store(store_dir, zip_path):
    if os.path.exists(zip_path):
        os.remove(zip_path)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for r, _, fs in os.walk(store_dir):
            for fn in fs:
                p = os.path.join(r, fn)
                z.write(p, os.path.relpath(p, store_dir))
    return os.path.getsize(zip_path)


YAML = """# FIM site: Comoros, {name} ({pcode}), {island_label}. Pluvial only, per municipality.
# Generated by fim_dev/build_comoros_stores.py from the {island} island model.
# Depths come from the model maximum depth rasters (float64 metres, stored at
# 1 cm precision). Magnitudes are REAL RainyDay storm totals: the area
# weighted mean of the band summed {box} scenario rain over this
# municipality. In orchestrated runs the fim_regions block in
# Caribbean_Comoros_config.py switches the whole country and overrides the
# thresholds below.
region: Comoros_{slug}

outputs_root: outputs
cycle_format: "%Y%m%d.%H%M%S"

aoc_geojson: fim_config/aoc/Comoros_{pcode}_{slug}_aoc.geojson
store: fim_store/Comoros/{store}
products_root: outputs/Comoros/fim_{pcode}_{slug}

member:
  template: "tmp_output_crest_scampr_{{qpf}}"

trigger:
  threshold: 1.0
  sources:
    - template: "tmp_output_crest_scampr_{{qpf}}"

hazards:
  pluvial:
    enabled: true
    grid: qpe_accum
    band: [0.9, 1.2]
    band_wide: [0.8, 1.3]
  fluvial:
    enabled: false

thresholds_m: [0.10, 0.30, 0.70, 1.00]

overbank:
  enabled: true
  reference_scenario: {overbank}

sampling:
  expand_steps_km: [0, 2, 5, 10, 15]
  min_valid_cells: 25

likelihood_bands:
  very_low: [0.0, 0.2]
  low: [0.2, 0.4]
  medium: [0.4, 0.6]
  high: [0.6, 1.01]
"""


def main():
    index = json.load(open(INDEX))
    mags_all = json.load(open(MAGS))
    adm = gpd.read_file(SHP)
    os.makedirs(f"{OUT}/fim_store/Comoros", exist_ok=True)
    os.makedirs(f"{OUT}/fim_config/aoc", exist_ok=True)

    manifest = []
    per_unit = {}
    only = sys.argv[1] if len(sys.argv) > 1 else None

    for adm1, island in ISLAND_OF.items():
        if only and only != island:
            continue
        with rasterio.open(f"{REF}/ref_{island}.tif") as src:
            crs, transform = src.crs, src.transform
            GW, GH = src.width, src.height
        print(f"== {island} ({adm1}): loading 200 scenarios", flush=True)
        ids, stack = load_island_stack(island, index)
        sub = adm[adm.adm1_pcode == adm1]
        sub_p = sub.to_crs(crs)
        print(f"   stack {stack.shape} {stack.nbytes/1e6:.0f} MB, {len(sub)} municipalities", flush=True)

        for (_, r), (_, rp) in zip(sub.iterrows(), sub_p.iterrows()):
            pcode, name = r.adm3_pcode, r.adm3_name
            sl = slug(name)
            minx, miny, maxx, maxy = rp.geometry.bounds
            c0 = int(np.floor((minx - transform.c) / transform.a)) - BUF
            c1 = int(np.ceil((maxx - transform.c) / transform.a)) + BUF
            r0 = int(np.floor((maxy - transform.f) / transform.e)) - BUF
            r1 = int(np.ceil((miny - transform.f) / transform.e)) + BUF
            c0, r0 = max(0, c0), max(0, r0)
            c1, r1 = min(GW, c1), min(GH, r1)
            if c1 <= c0 or r1 <= r0:
                print(f"   {pcode} {name}: NO OVERLAP with the island grid, skipped")
                continue
            win_transform = rasterio.windows.transform(
                Window(c0, r0, c1 - c0, r1 - r0), transform)

            m = mags_all["magnitudes"][pcode]
            order = sorted(ids, key=lambda s: m[s])
            mags = np.array([m[s] for s in order], dtype="float64")
            store_name = f"fim_store_{pcode}_{sl}_v1.zarr"
            out = f"{OUT}/fim_store/Comoros/{store_name}"
            shutil.rmtree(out, ignore_errors=True)
            root = zarr.open_group(out, mode="w")
            ny, nx = r1 - r0, c1 - c0
            n = len(order)
            depth = create(root, "depth", (n, ny, nx), "float32", (1, ny, nx))
            extent = create(root, "extent", (n, ny, nx), "uint8", (1, ny, nx))
            pos = {s: i for i, s in enumerate(ids)}
            for k, s in enumerate(order):
                a = (stack[pos[s], r0:r1, c0:c1].astype("float32")) / 100.0
                depth[k] = a
                extent[k] = (a >= EXTENT_M).astype("uint8")
            ma = create(root, "magnitude_mm", (n,), "float64", (n,))
            ma[:] = mags
            L = max(len(s) for s in order)
            sid = create(root, "storm_id", (n,), f"S{L}", (n,))
            sid[:] = np.array([s.encode() for s in order], dtype=f"S{L}")
            root.attrs.update({
                "crs": str(crs), "transform": list(np.asarray(win_transform)[:6]),
                "extent_threshold_m": EXTENT_M, "source_nodata": None,
                "magnitude_source": (
                    "real RainyDay storm totals: area weighted mean over the "
                    f"municipality of the band summed {BOX_OF[island]} scenario "
                    "rain geotiff (200 scenarios, 72 bands, 0.027 degree grid)"),
                "n_storms": n, "grid_shape": [ny, nx],
                "depth_source": (f"{island} island model maximum depth rasters "
                                 "(float64 metres), stored at 1 cm precision"),
                "admin_unit": {"pcode": pcode, "name": name,
                               "adm1": r.adm1_name, "adm2": r.adm2_name},
            })
            with open(os.path.join(out, "index.csv"), "w", newline="") as fh:
                w = csv.writer(fh)
                w.writerow(["storm_index", "storm_id", "magnitude_mm"])
                for i, (s, mm) in enumerate(zip(order, mags)):
                    w.writerow([i, s, round(float(mm), 2)])
            with open(os.path.join(out, "meta.json"), "w") as fh:
                json.dump(dict(root.attrs), fh, indent=2)
            size = zip_store(out, out + ".zip")
            shutil.rmtree(out)

            gj = {"type": "FeatureCollection", "features": [{
                "type": "Feature",
                "properties": {"country": "Comoros", "pcode": pcode, "name": name,
                               "island": r.adm1_name},
                "geometry": json.loads(gpd.GeoSeries([r.geometry], crs=adm.crs).to_json())
                            ["features"][0]["geometry"]}]}
            with open(f"{OUT}/fim_config/aoc/Comoros_{pcode}_{sl}_aoc.geojson", "w") as fh:
                json.dump(gj, fh)
            with open(f"{OUT}/fim_config/Comoros_{sl}.yaml", "w") as fh:
                fh.write(YAML.format(name=name, pcode=pcode, island=island,
                                     island_label=r.adm1_name, box=BOX_OF[island],
                                     slug=sl, store=store_name, overbank=order[0]))
            wet = float((stack[:, r0:r1, c0:c1] >= EXTENT_M * 100).mean())
            manifest.append([pcode, name, r.adm1_name, island, store_name, n,
                             f"{nx}x{ny}", round(float(mags.min()), 1),
                             round(float(mags.max()), 1), round(size / 1e6, 2),
                             round(wet * 100, 2)])
            per_unit[pcode] = {"name": name, "island": r.adm1_name,
                               "island_model": island, "n_scenarios": n,
                               "magnitudes_mm": m}
            print(f"   {pcode} {name[:22]:<22} {nx:>4}x{ny:<4} zip {size/1e6:6.2f} MB "
                  f"mm[{mags.min():6.1f}..{mags.max():6.1f}] wet {wet*100:4.1f}%", flush=True)
        del stack

    mode = "a" if only and os.path.exists(f"{OUT}/manifest_Comoros.csv") else "w"
    with open(f"{OUT}/manifest_Comoros.csv", mode, newline="") as fh:
        w = csv.writer(fh)
        if mode == "w":
            w.writerow(["pcode", "name", "island", "island_model", "store", "n_scenarios",
                        "grid_wxh", "magnitude_min_mm", "magnitude_max_mm", "zip_mb",
                        "wet_cells_pct"])
        w.writerows(manifest)
    jp = f"{OUT}/magnitudes_Comoros_per_unit.json"
    if only and os.path.exists(jp):
        old = json.load(open(jp)); old.update(per_unit); per_unit = old
    json.dump(per_unit, open(jp, "w"), indent=1)
    print(f"\nwrote {len(manifest)} stores this run")


if __name__ == "__main__":
    main()
